                services:
  - type: worker  # <-- Было "web", стало "worker"
    name: aiobot
    env: python
    pythonVersion: 3.11
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false