services:
  - type: web
    name: aiobot
    env: python
    pythonVersion: 3.11
    buildCommand: |
      python --version
      pip --version
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false